version: "3.7"
services:
        data-analysis:
                container_name: sqlite
                build: .
                volumes:
                        - dbdata:/data
volumes:
        dbdata:
                driver_opts:
                        device: './'

